//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SearchEngine.com.ebay.developer1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FeedbackServiceSOAPBinding", Namespace="http://www.ebay.com/marketplace/services")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseServiceResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseServiceRequest))]
    public partial class FeedbackService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createDSRSummaryByTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback createDSRSummaryByPeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback createDSRSummaryByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback createDSRSummaryByShippingDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDSRSummaryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FeedbackService() {
            this.Url = global::SearchEngine.Properties.Settings.Default.SearchEngine_com_ebay_developer1_FeedbackService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createDSRSummaryByTransactionCompletedEventHandler createDSRSummaryByTransactionCompleted;
        
        /// <remarks/>
        public event createDSRSummaryByPeriodCompletedEventHandler createDSRSummaryByPeriodCompleted;
        
        /// <remarks/>
        public event createDSRSummaryByCategoryCompletedEventHandler createDSRSummaryByCategoryCompleted;
        
        /// <remarks/>
        public event createDSRSummaryByShippingDetailCompletedEventHandler createDSRSummaryByShippingDetailCompleted;
        
        /// <remarks/>
        public event getDSRSummaryCompletedEventHandler getDSRSummaryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createDSRSummaryByTransaction", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createDSRSummaryResponse", Namespace="http://www.ebay.com/marketplace/services")]
        public CreateDSRSummaryResponse createDSRSummaryByTransaction([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ebay.com/marketplace/services")] CreateDSRSummaryByTransactionRequest createDSRSummaryByTransactionRequest) {
            object[] results = this.Invoke("createDSRSummaryByTransaction", new object[] {
                        createDSRSummaryByTransactionRequest});
            return ((CreateDSRSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createDSRSummaryByTransactionAsync(CreateDSRSummaryByTransactionRequest createDSRSummaryByTransactionRequest) {
            this.createDSRSummaryByTransactionAsync(createDSRSummaryByTransactionRequest, null);
        }
        
        /// <remarks/>
        public void createDSRSummaryByTransactionAsync(CreateDSRSummaryByTransactionRequest createDSRSummaryByTransactionRequest, object userState) {
            if ((this.createDSRSummaryByTransactionOperationCompleted == null)) {
                this.createDSRSummaryByTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateDSRSummaryByTransactionOperationCompleted);
            }
            this.InvokeAsync("createDSRSummaryByTransaction", new object[] {
                        createDSRSummaryByTransactionRequest}, this.createDSRSummaryByTransactionOperationCompleted, userState);
        }
        
        private void OncreateDSRSummaryByTransactionOperationCompleted(object arg) {
            if ((this.createDSRSummaryByTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createDSRSummaryByTransactionCompleted(this, new createDSRSummaryByTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createDSRSummaryByPeriod", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createDSRSummaryResponse", Namespace="http://www.ebay.com/marketplace/services")]
        public CreateDSRSummaryResponse createDSRSummaryByPeriod([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ebay.com/marketplace/services")] CreateDSRSummaryByPeriodRequest createDSRSummaryByPeriodRequest) {
            object[] results = this.Invoke("createDSRSummaryByPeriod", new object[] {
                        createDSRSummaryByPeriodRequest});
            return ((CreateDSRSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createDSRSummaryByPeriodAsync(CreateDSRSummaryByPeriodRequest createDSRSummaryByPeriodRequest) {
            this.createDSRSummaryByPeriodAsync(createDSRSummaryByPeriodRequest, null);
        }
        
        /// <remarks/>
        public void createDSRSummaryByPeriodAsync(CreateDSRSummaryByPeriodRequest createDSRSummaryByPeriodRequest, object userState) {
            if ((this.createDSRSummaryByPeriodOperationCompleted == null)) {
                this.createDSRSummaryByPeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateDSRSummaryByPeriodOperationCompleted);
            }
            this.InvokeAsync("createDSRSummaryByPeriod", new object[] {
                        createDSRSummaryByPeriodRequest}, this.createDSRSummaryByPeriodOperationCompleted, userState);
        }
        
        private void OncreateDSRSummaryByPeriodOperationCompleted(object arg) {
            if ((this.createDSRSummaryByPeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createDSRSummaryByPeriodCompleted(this, new createDSRSummaryByPeriodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createDSRSummaryByCategory", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createDSRSummaryResponse", Namespace="http://www.ebay.com/marketplace/services")]
        public CreateDSRSummaryResponse createDSRSummaryByCategory([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ebay.com/marketplace/services")] CreateDSRSummaryByCategoryRequest createDSRSummaryByCategoryRequest) {
            object[] results = this.Invoke("createDSRSummaryByCategory", new object[] {
                        createDSRSummaryByCategoryRequest});
            return ((CreateDSRSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createDSRSummaryByCategoryAsync(CreateDSRSummaryByCategoryRequest createDSRSummaryByCategoryRequest) {
            this.createDSRSummaryByCategoryAsync(createDSRSummaryByCategoryRequest, null);
        }
        
        /// <remarks/>
        public void createDSRSummaryByCategoryAsync(CreateDSRSummaryByCategoryRequest createDSRSummaryByCategoryRequest, object userState) {
            if ((this.createDSRSummaryByCategoryOperationCompleted == null)) {
                this.createDSRSummaryByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateDSRSummaryByCategoryOperationCompleted);
            }
            this.InvokeAsync("createDSRSummaryByCategory", new object[] {
                        createDSRSummaryByCategoryRequest}, this.createDSRSummaryByCategoryOperationCompleted, userState);
        }
        
        private void OncreateDSRSummaryByCategoryOperationCompleted(object arg) {
            if ((this.createDSRSummaryByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createDSRSummaryByCategoryCompleted(this, new createDSRSummaryByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createDSRSummaryByShippingDetail", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createDSRSummaryResponse", Namespace="http://www.ebay.com/marketplace/services")]
        public CreateDSRSummaryResponse createDSRSummaryByShippingDetail([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ebay.com/marketplace/services")] CreateDSRSummaryByShippingDetailRequest createDSRSummaryByShippingDetailRequest) {
            object[] results = this.Invoke("createDSRSummaryByShippingDetail", new object[] {
                        createDSRSummaryByShippingDetailRequest});
            return ((CreateDSRSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createDSRSummaryByShippingDetailAsync(CreateDSRSummaryByShippingDetailRequest createDSRSummaryByShippingDetailRequest) {
            this.createDSRSummaryByShippingDetailAsync(createDSRSummaryByShippingDetailRequest, null);
        }
        
        /// <remarks/>
        public void createDSRSummaryByShippingDetailAsync(CreateDSRSummaryByShippingDetailRequest createDSRSummaryByShippingDetailRequest, object userState) {
            if ((this.createDSRSummaryByShippingDetailOperationCompleted == null)) {
                this.createDSRSummaryByShippingDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateDSRSummaryByShippingDetailOperationCompleted);
            }
            this.InvokeAsync("createDSRSummaryByShippingDetail", new object[] {
                        createDSRSummaryByShippingDetailRequest}, this.createDSRSummaryByShippingDetailOperationCompleted, userState);
        }
        
        private void OncreateDSRSummaryByShippingDetailOperationCompleted(object arg) {
            if ((this.createDSRSummaryByShippingDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createDSRSummaryByShippingDetailCompleted(this, new createDSRSummaryByShippingDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getDSRSummary", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getDSRSummaryResponse", Namespace="http://www.ebay.com/marketplace/services")]
        public GetDSRSummaryResponse getDSRSummary([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ebay.com/marketplace/services")] GetDSRSummaryRequest getDSRSummaryRequest) {
            object[] results = this.Invoke("getDSRSummary", new object[] {
                        getDSRSummaryRequest});
            return ((GetDSRSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getDSRSummaryAsync(GetDSRSummaryRequest getDSRSummaryRequest) {
            this.getDSRSummaryAsync(getDSRSummaryRequest, null);
        }
        
        /// <remarks/>
        public void getDSRSummaryAsync(GetDSRSummaryRequest getDSRSummaryRequest, object userState) {
            if ((this.getDSRSummaryOperationCompleted == null)) {
                this.getDSRSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDSRSummaryOperationCompleted);
            }
            this.InvokeAsync("getDSRSummary", new object[] {
                        getDSRSummaryRequest}, this.getDSRSummaryOperationCompleted, userState);
        }
        
        private void OngetDSRSummaryOperationCompleted(object arg) {
            if ((this.getDSRSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDSRSummaryCompleted(this, new getDSRSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class CreateDSRSummaryByTransactionRequest : BaseServiceRequest {
        
        private TransactionKey[] transactionKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactionKey")]
        public TransactionKey[] transactionKey {
            get {
                return this.transactionKeyField;
            }
            set {
                this.transactionKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class TransactionKey {
        
        private string itemIdField;
        
        private string transactionIdField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string itemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class DSRSummary {
        
        private string dSRTypeField;
        
        private double dSRAverageField;
        
        private int totalRatingCountField;
        
        private int rating1CountField;
        
        private int rating2CountField;
        
        private int rating3CountField;
        
        private int rating4CountField;
        
        private int rating5CountField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string DSRType {
            get {
                return this.dSRTypeField;
            }
            set {
                this.dSRTypeField = value;
            }
        }
        
        /// <remarks/>
        public double DSRAverage {
            get {
                return this.dSRAverageField;
            }
            set {
                this.dSRAverageField = value;
            }
        }
        
        /// <remarks/>
        public int totalRatingCount {
            get {
                return this.totalRatingCountField;
            }
            set {
                this.totalRatingCountField = value;
            }
        }
        
        /// <remarks/>
        public int rating1Count {
            get {
                return this.rating1CountField;
            }
            set {
                this.rating1CountField = value;
            }
        }
        
        /// <remarks/>
        public int rating2Count {
            get {
                return this.rating2CountField;
            }
            set {
                this.rating2CountField = value;
            }
        }
        
        /// <remarks/>
        public int rating3Count {
            get {
                return this.rating3CountField;
            }
            set {
                this.rating3CountField = value;
            }
        }
        
        /// <remarks/>
        public int rating4Count {
            get {
                return this.rating4CountField;
            }
            set {
                this.rating4CountField = value;
            }
        }
        
        /// <remarks/>
        public int rating5Count {
            get {
                return this.rating5CountField;
            }
            set {
                this.rating5CountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class ErrorParameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class ErrorData {
        
        private long errorIdField;
        
        private string domainField;
        
        private ErrorSeverity severityField;
        
        private ErrorCategory categoryField;
        
        private string messageField;
        
        private string subdomainField;
        
        private string exceptionIdField;
        
        private ErrorParameter[] parameterField;
        
        /// <remarks/>
        public long errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
            }
        }
        
        /// <remarks/>
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public ErrorSeverity severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public ErrorCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string subdomain {
            get {
                return this.subdomainField;
            }
            set {
                this.subdomainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public ErrorParameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum ErrorSeverity {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum ErrorCategory {
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        Request,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDSRSummaryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDSRSummaryResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public abstract partial class BaseServiceResponse {
        
        private AckValue ackField;
        
        private ErrorData[] errorMessageField;
        
        private string versionField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        public AckValue ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public ErrorData[] errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum AckValue {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        PartialFailure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class GetDSRSummaryResponse : BaseServiceResponse {
        
        private DSRSummary[] dSRSummaryField;
        
        private int totalTransactionCountField;
        
        private bool totalTransactionCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DSRSummary")]
        public DSRSummary[] DSRSummary {
            get {
                return this.dSRSummaryField;
            }
            set {
                this.dSRSummaryField = value;
            }
        }
        
        /// <remarks/>
        public int totalTransactionCount {
            get {
                return this.totalTransactionCountField;
            }
            set {
                this.totalTransactionCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalTransactionCountSpecified {
            get {
                return this.totalTransactionCountFieldSpecified;
            }
            set {
                this.totalTransactionCountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class CreateDSRSummaryResponse : BaseServiceResponse {
        
        private string jobIdField;
        
        /// <remarks/>
        public string jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class DateRange {
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        /// <remarks/>
        public System.DateTime dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDSRSummaryRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDSRSummaryByShippingDetailRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDSRSummaryByCategoryRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDSRSummaryByPeriodRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateDSRSummaryByTransactionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public abstract partial class BaseServiceRequest {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class GetDSRSummaryRequest : BaseServiceRequest {
        
        private string jobIdField;
        
        /// <remarks/>
        public string jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class CreateDSRSummaryByShippingDetailRequest : BaseServiceRequest {
        
        private DateRange dateRangeField;
        
        private string dateRangeEventTypeField;
        
        private string shippingCostTypeField;
        
        private string shippingDestinationTypeField;
        
        private string[] shipToCountryField;
        
        private string[] shippingServiceField;
        
        /// <remarks/>
        public DateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string dateRangeEventType {
            get {
                return this.dateRangeEventTypeField;
            }
            set {
                this.dateRangeEventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string shippingCostType {
            get {
                return this.shippingCostTypeField;
            }
            set {
                this.shippingCostTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string shippingDestinationType {
            get {
                return this.shippingDestinationTypeField;
            }
            set {
                this.shippingDestinationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipToCountry", DataType="token")]
        public string[] shipToCountry {
            get {
                return this.shipToCountryField;
            }
            set {
                this.shipToCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippingService", DataType="token")]
        public string[] shippingService {
            get {
                return this.shippingServiceField;
            }
            set {
                this.shippingServiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class CreateDSRSummaryByCategoryRequest : BaseServiceRequest {
        
        private DateRange dateRangeField;
        
        private string dateRangeEventTypeField;
        
        private string[] categoryIdField;
        
        /// <remarks/>
        public DateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string dateRangeEventType {
            get {
                return this.dateRangeEventTypeField;
            }
            set {
                this.dateRangeEventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categoryId")]
        public string[] categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class CreateDSRSummaryByPeriodRequest : BaseServiceRequest {
        
        private DateRange dateRangeField;
        
        private string dateRangeEventTypeField;
        
        /// <remarks/>
        public DateRange dateRange {
            get {
                return this.dateRangeField;
            }
            set {
                this.dateRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string dateRangeEventType {
            get {
                return this.dateRangeEventTypeField;
            }
            set {
                this.dateRangeEventTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void createDSRSummaryByTransactionCompletedEventHandler(object sender, createDSRSummaryByTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createDSRSummaryByTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createDSRSummaryByTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDSRSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDSRSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void createDSRSummaryByPeriodCompletedEventHandler(object sender, createDSRSummaryByPeriodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createDSRSummaryByPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createDSRSummaryByPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDSRSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDSRSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void createDSRSummaryByCategoryCompletedEventHandler(object sender, createDSRSummaryByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createDSRSummaryByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createDSRSummaryByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDSRSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDSRSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void createDSRSummaryByShippingDetailCompletedEventHandler(object sender, createDSRSummaryByShippingDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createDSRSummaryByShippingDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createDSRSummaryByShippingDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateDSRSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateDSRSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getDSRSummaryCompletedEventHandler(object sender, getDSRSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDSRSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDSRSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDSRSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDSRSummaryResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591